### ISSUE TITLE
Gathering Elevation Survey Data

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#36]
### User Story

In order to develop elevation survey extents, as an LDA I need to collect the tile extent data from the LDS.

#### Acceptance Criteria- [ ] 
- [x] Talk to Imagery team to get spreadsheet of datasets
- [x] Get data from LDS and open topography

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by Douglas-K** [comment]
List of datasets obtained from imagery team.
All DEM, DSM, and tile extents are saved on the LDS staging server.  We now have access to this.
Imagery team have told us the tile extents of the first 12 datasets were directly from the flying companies and have not been QA'd.  The tile extents since then have been QA'd and are correct.
We have regenerated the tile extents for the first 12 datasets based on where the LINZ 1k tiles intersect with DEM and DSM data.  These have been saved onto S drive.
Point Cloud extents have been extracted from Open Topography and saved onto S drive.
